<!DOCTYPE html>
<html>
<body>
Registration
<div>
    <form method="post" action="/register">
        <p><input type="text" name="username" placeholder="Введите логин" size="18" /></p>
        <p><input type="text" name="firstName" placeholder="Введите имя" size="18" /></p>
        <p><input type="text" name="lastName" placeholder="Введите фамилию" size="18" /></p>
        <p><input type="text" name="email" placeholder="Введите email" size="18" /></p>
        <p>
            <button type="submit">Отправить</button>
        </p>
    </form>
</div>
</body>
</html>